### ISSUE TITLE
dumpster colliders went missing

### ISSUE THREAD

**Issue by blair123xyz** [owlboy/greatpug-public#99]
**Describe the Bug**: left dumpster doesnt have colliders on the outside, only on the trashbags

**Steps To Reproduce**: walk through walls of dumpster instead of colliding/jumping on top of it

**Expected Behavior**: dumpster walls had colliders before most recent update

**Screenshots**: lol   
![VRChat_2023-05-15_06-37-25 452_1920x1080_wrld_6caf5200-70e1-46c2-b043-e3c4abe69e0f](https://github.com/owlboy/greatpug-public/assets/112629268/a284949e-0335-4d7d-bbce-830944a4def2)

**Are you in VR or Desktop mode?** happens to both

**Comment by owlboy** [comment]
Thanks. I noticed this late last night and left it for fixing today. I appreciate the report!

**Comment by owlboy** [comment]
This should be fixed now! Sorry for the delay, and thank you for taking the time to report it!

https://github.com/owlboy/greatpug-public/releases/tag/2023.05.19

**Comment by blair123xyz** [comment]
Unfortunately it seems that this is still an issue, I've reloaded the world a few times and it still has no colliders :(

**Comment by owlboy** [comment]
Whoops! I put the collider back, but I didn't notice the object I placed it on was marked EditorOnly! And strangely, ClientSim did not remove it as I would have expected. So when testing in the Editor, the collider was working.

This should be fixed for real now. Thanks for checking in on it!

**Comment by owlboy** [comment]
Oh, I see why EditorOnly does not work here:
https://github.com/vrchat-community/ClientSim/issues/33

**Comment by blair123xyz** [comment]
Works perfect again, thank you so much ^_^

**Comment by blair123xyz** [comment]
same colliders missing again since the last update 😅

**Comment by owlboy** [comment]
What! Weird! I'll take a look at this for the next build.
